import type { GetStaticPropsContext, NextPage } from 'next';
import Head from 'next/head';
import Image from 'next/image';
import Link from 'next/link';
import { useEffect } from 'react';
import { getPostsForHome } from '../src/apollo/api';
import client from '../src/apollo/client';
import { GET_PAGE } from '../src/queries/pages/get-page';
import { GET_PAGES_URI } from '../src/queries/pages/get-pages';
import { handleRedirectsAndReturnData } from '../src/utils/slug';
import styles from '../styles/Home.module.css';

const Home: NextPage = ({ posts }: any) => {
  console.log(posts);
  return (
    <div className={styles.container}>
      <Head>
        <title>Headless Datgate</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <div className={styles.grid}>
          {posts.map(({ node }: any, idx: any) => (
            <div key={idx} className={styles.card}>
              <Link href={`/blog/` + node.slug} passHref>
                <h2>{node.title}</h2>
              </Link>

              <p>{node.date}</p>
            </div>
          ))}
          <Link className={styles.card} href="/srp">
            <h2>SRP</h2>
          </Link>
        </div>
      </main>
    </div>
  );
};

export async function getStaticProps(context: GetStaticPropsContext) {
  const posts = await getPostsForHome();

  return {
    props: { posts: posts.edges },
  };
  // const { data, errors } = await client.query({
  //   query: GET_PAGE,
  //   variables: {
  //     uri: '/',
  //   },
  // });

  // const defaultProps = {
  //   props: {
  //     data: data || {},
  //   },
  //   revalidate: 1,
  // };

  // return handleRedirectsAndReturnData(defaultProps, data, errors, 'page');
}

export default Home;
